### ISSUE TITLE
Cleanup Unknown Songs by Title and Artist Name

### ISSUE THREAD

**Issue by lauhub** [NBS-LLC/ng-spotify-importer#15]
Song recognition could be enhanced when a song is not recognized by doing the following:

- remove the parenthesis part in song title. E.g.: `Life On Mars? (Live at Fashion Rocks)`=> `Life On Mars?`
- remove the ampersand sign `&` from title or artist name
- remove all the parts after the ampersand sign `&` in title or artist name:  `Descemer Bueno & Issac Delgado` => `Descemer Bueno`
- remove singloe quote `'` in title and/or artist: `Ben L'Oncle Soul` => `Ben LOncle Soul`
- remove "Featurings" : `Gloria Estefan Feat. Wisin Y Yandel` => `Gloria Estefan`

I applied these manually on unknown tracks and got good results (90% of unrecognized songs became recognized)

**Comment by NBS-LLC** [comment]
Tag v1.4.0 includes this fix which has been deployed to a staging environment:
https://stg.nickwanders.com/projects/ng-spotify-importer/

**Comment by NBS-LLC** [comment]
Version 1.4.0 has been deployed to production. Closing this issue.
