### ISSUE TITLE
CSV Load Error

### ISSUE THREAD

**Issue by mtmcnall** [NBS-LLC/ng-spotify-importer#198]
I have this file with two columns, title and artist, but code keeps giving me an error. Do you know why? It used to work flawlessly with the same template.
[Book1.csv](https://github.com/NBS-LLC/ng-spotify-importer/files/8923773/Book1.csv)

**Comment by NBS-LLC** [comment]
Give version 1.4.0 a try, which can be found here: https://stg.nickwanders.com/projects/ng-spotify-importer

I noticed I was parsing Unicode incorrectly in the release version, 1.3.0. Which I fixed in the pre-release version, 1.4.0.

**Comment by georgedimac** [comment]
1.4.0 does not work at all, only API/token errors. 1.3.0 works ok but has trouble with ' character in names.

**Comment by NBS-LLC** [comment]
@mtmcnall is this still an issue? I can't seem to fully replicate the issue in Staging (1.4.0). The CSV is parsed and imports correctly. With the exception of 4 songs it cannot find.

However I do see some possible text encoding issues. Though these seem present in the original CSV:

![image](https://user-images.githubusercontent.com/35822984/208280009-7aea939e-53cf-4a2c-b367-dd92803300b8.png)

![Screenshot 2022-12-17 6 49 53 PM](https://user-images.githubusercontent.com/35822984/208280019-25c1ef0e-7667-4459-9b5f-17a00ff95536.png)

**Comment by NBS-LLC** [comment]
@georgedimac if you are still running into API/token issues please create a new ticket with screenshots and/or error messages. Thank you :)

**Comment by NBS-LLC** [comment]
Version 1.4.0 has been deployed to production. If any of the issues reported in this ticket have surfaced please open new, separate tickets. Closing.
