### ISSUE TITLE
Limit to number of tracks imported

### ISSUE THREAD

**Issue by ghidorahbilbo** [NBS-LLC/ng-spotify-importer#200]
Hi there, great tool, been using it for a few months now!

Last time I used the tool was in April of 2022 and I'm checking it out now and I can't seem to get it to load completely with CSVs of than 100 tracks. Works perfectly up to 100, but any more and it doesn't ever finish completely anymore like it used to. 

(You can see in the attached PNGs that the loading bar gets right up the edge but isn't completely finished.)

I used to be able to import lists of over 650+ but now I have to split it up into multiple CSVs and collate my separate lists into 1 in the Spotify app.

I'm having this issue using both 1.3.0 and your latest 1.4.0 on Chrome, Firefox, and Edge, all getting the same result after having tried multiple CSVs of different numbers over 100.

I was trying to import a list of 600+ today and tried deleting 50 at a time, 550, 500, 450, etc and found that the highest number of tracks that works (at intervals of 50) is 100, across all 3 browsers for me.

Would gladly tip you for releasing this hella useful tool, where can I do that?

![NG Spotify Importer 1 3 0 1](https://user-images.githubusercontent.com/109384755/179293566-303da1c6-9561-4b45-80eb-00e614c3d2ed.png)
![NG Spotify Importer 1 4 0 1](https://user-images.githubusercontent.com/109384755/179293568-67e8727d-a323-482f-8ce1-ea7f4f4c5994.png)

**Comment by ghidorahbilbo** [comment]
Update - I ended up figuring out my issue. There were too many characters in a particular track title, a remix with lots of extra words. 

Figured it out when I was splitting up my huge list into CSV files that contained smaller batches of 100. All the batches of 100 worked well until the one with said long track title. Figured it was the long length so I deleted half of the track title and that ended up working.

Once that worked, I figured I might as well try my huge list of 600+ again with the shorter track title in the data field, and sure enough, the progress bar completed, everything was found and it was imported perfectly.

Don't know exactly how many is too many characters until it breaks, I will sit down soon and toy with it to see.

**Comment by mattgrosso** [comment]
I've run into a similar issue and done a bit of digging myself. For anyone else running into this issue, here's what I found:

- fields that have more than 81 characters seem to break the API
- There are a couple of specific characters that will break it as well. The two that I found in my playlists are `-` and `,` bu there may be others.

You can sort of understand the issue with commas in a csv but I'm surprised that `-` causes trouble because other operators don't.

The 81 character limit is strange to me because it's such a specific number but 🤷‍♂️

**Comment by NBS-LLC** [comment]
Is this still an issue? If so can you provide some sample CSV files? Preferably the smallest set of songs that can replicate this issue.

I tried with title: `Mr. Capgras Encounters a Secondhand Vanity: Tulpamancer’s Prosopagnosia​/​Pareidolia (As Direct Result of Trauma to the Fusiform Gyrus)` which is 136 characters and that imported correctly in both Staging (1.3.0) and Production (1.4.0).

**Comment by NBS-LLC** [comment]
Version 1.4.0 has been deployed to production. If any of these issues surface in v1.4.0 please open new, separate issues. Closing.
