### ISSUE TITLE
Is loading the song but not create playlist and add the songs to it

### ISSUE THREAD

**Issue by mikebgrep** [NBS-LLC/ng-spotify-importer#203]
I just find the tool is very good solution, but I try 1.4.0 and is not working some issue with the token on 1.3.0 from the link in the description I manage to load the songs into the tool, but they are not appearing on my Spotify account after this In network tab I only see GET requests. Is that normal behavior. From this I read is need to create a playlist and add the songs in it.

**Comment by NBS-LLC** [comment]
Is this still an issue? If so, can you take a screenshot of the error you are getting? Thank you :)

**Comment by NBS-LLC** [comment]
Closing this ticket due to lack of activity.

Version 1.4.0 has been deployed to production today. If this remains an issue please submit a new ticket.

**Comment by Michan17** [comment]
I have the same issue too. It seems like the playlist not created on my Spotify. Is it will be created as I start to import the playlist or after the progress already finish? FYI, I have 20.718 data in my CSV. I've already wait for long time to load all of my playlist but when it's finished, the playlist is not appear on My Spotify Account. Can you help me handle this issue?
