### ISSUE TITLE
Specific song is not found

### ISSUE THREAD

**Issue by NBS-LLC** [NBS-LLC/ng-spotify-importer#217]
Title: Que Sera
Artist: Wax Tailor

More details in the original [post](https://community.spotify.com/t5/App-Features/I-ve-Created-a-FREE-CSV-Playlist-Import-Tool/m-p/5494108/highlight/true#M6643).

**Comment by greenythebeast** [comment]
Another example for you:

Title: Hearts on Fire
Artist: ILLENIUM, Dabin, Lights

If I use your tool to search for Hearts on Fire by ILLENIUM or Dabin, nothing comes up. However, if I search for Hearts on Fire by Lights, it does show up. So it seems the tool is struggling when there are more than one artist?

**Comment by NBS-LLC** [comment]
I cannot reproduce the original issue:

![image](https://user-images.githubusercontent.com/35822984/237001436-2dddceab-67a4-4ec0-b63a-a22237ecfe04.png)

But as @greenythebeast points out, songs with multiple artists are not found (see 2nd track in the screenshot above).

**Comment by NBS-LLC** [comment]
Turns out this was a simple bug in how this project uses Spotify's API. It was wrapping the song title and artist name in double quotes. Probably with the intention of ensuring spaces are handled properly. The Spotify API already handles spaces by URI encoding, so quotes are not needed. When the quotes are removed it allows Spotify's search algorithm to do a more relaxed search resulting in better matches.

In my above observation, adding another set of double quotes cancels out the already existing (not shown in the UI) double quotes. Again allowing for a more relaxed search and thus matching the intended song.
