### ISSUE TITLE
A button to swap artist and title

### ISSUE THREAD

**Issue by SpitFire-666** [NBS-LLC/ng-spotify-importer#259]
When trying to find unknown tracks, it would be handy to have a "swap fields" button in case the CSV has artist and title around the wrong way, OR if you have songs that you don't know which field is the actual artist or title. Cheers

**Comment by NBS-LLC** [comment]
I appreciate the feedback. However, I won't be including this enhancement. If the entire CSV has the artist and title swapped it would be easier to use a text editor (or Excel, Sheets, etc) to simply transpose the column **names**. Similarly for one offs- copy / paste would work.
